name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2


    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o msauth.exe -trimpath -ldflags "-w -s" main.go
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o msauth-linux -trimpath -ldflags "-w -s" main.go
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o msauth-darwin -trimpath -ldflags "-w -s" main.go

    - name: Test
      run: go test -v ./...

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
       # A file, directory or wildcard pattern that describes what to upload
       path: ./msauth*
       name:  ${{ github.run_number }}
